### ISSUE TITLE
Support for 4.17?

### ISSUE THREAD

**Issue by chriship** [getnamo/myo-ue4#6]
Is there support for UE4.17?

**Comment by getnamo** [comment]
Nothing that works out of the box as of right now.

I've been neglecting this repository for quite a while now, but I've been trying to find the time to wrap up the modern rewrite (fork found here: https://github.com/getnamo/myo-ue4/compare/hub-packaging-fixes). Whenever that gets done it will get a 4.17 or newer release. 

Otherwise you can try to take the current master repository and recompile it for 4.17, there will likely be some compiles fixes due to UE api changes, but they shouldn't be too daunting.

**Comment by getnamo** [comment]
4.18 is now supported in the early modern rewrite release merge here: https://github.com/getnamo/myo-ue4/commit/6d1d87c29c3236ac320060da8ed88180a41c8ff6. Grab the latest release here: https://github.com/getnamo/myo-ue4/releases
